package dev.groundwork.template;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.List;

public final class TemplateDraftWriter {
    public void write(Path target, TemplateDraftRequest request, boolean overwrite) throws IOException {
        Path parent = target.toAbsolutePath().normalize().getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        if (Files.exists(target) && !overwrite) {
            throw new IllegalStateException("Template file already exists: " + target);
        }

        StandardOpenOption[] options = overwrite
                ? new StandardOpenOption[] {StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.WRITE}
                : new StandardOpenOption[] {StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE};

        Files.writeString(target, render(target, request, false), options);
    }

    public String render(TemplateDraftRequest request) {
        return render(null, request, false);
    }

    public String render(Path target, TemplateDraftRequest request, boolean preferRelativePaths) {
        List<String> lines = new ArrayList<>();
        lines.add("# Generated by Groundwork.");
        lines.add("# Global default strip patterns are applied automatically by the CLI.");
        lines.add("name: " + quote(request.name()));
        lines.add("description: " + quote(request.description()));
        lines.add("version: 1");

        if (!request.references().isEmpty()) {
            lines.add("references:");
            for (TemplateDraftReference reference : request.references()) {
                lines.add("  - repo: " + quote(renderPath(target, reference.repo(), preferRelativePaths)));
                if (reference.readFor() != null && !reference.readFor().isBlank()) {
                    lines.add("    read_for: " + quote(reference.readFor()));
                }
            }
        }

        if (!request.stripPatterns().isEmpty()) {
            lines.add("strip:");
            for (String stripPattern : request.stripPatterns()) {
                lines.add("  - " + quote(stripPattern));
            }
        }

        lines.add("claude_md:");
        lines.add("  template: " + quote(request.claudeTemplate()));
        lines.add("  variables:");
        lines.add("    project_name: " + quote("{{name}}"));
        lines.add("    description: " + quote("{{description}}"));

        if (request.generateReadme() || request.generateGitignore()) {
            lines.add("generate:");
            if (request.generateReadme()) {
                lines.add("  - README.md");
            }
            if (request.generateGitignore()) {
                lines.add("  - .gitignore: " + request.gitignoreProfile());
            }
        }

        if (!request.directories().isEmpty()) {
            lines.add("directories:");
            for (String directory : request.directories()) {
                lines.add("  - " + quote(directory));
            }
        }

        if (request.blueprint() != null) {
            lines.add("blueprint: " + quote(renderPath(target, request.blueprint(), preferRelativePaths)));
        }

        return String.join(System.lineSeparator(), lines) + System.lineSeparator();
    }

    private String renderPath(Path target, Path value, boolean preferRelativePaths) {
        Path normalizedValue = value.toAbsolutePath().normalize();
        if (!preferRelativePaths || target == null) {
            return normalizedValue.toString();
        }

        Path parent = target.toAbsolutePath().normalize().getParent();
        if (parent == null) {
            return normalizedValue.toString();
        }

        try {
            return parent.relativize(normalizedValue).toString();
        } catch (IllegalArgumentException exception) {
            return normalizedValue.toString();
        }
    }

    private String quote(String value) {
        return "\"" + value
                .replace("\\", "\\\\")
                .replace("\"", "\\\"") + "\"";
    }
}
